### ISSUE TITLE
想法挺好的，但是你这种方案侵入性太强了

### ISSUE THREAD

**Issue by Rowandjj** [maoruibin/ReView#2]

**Comment by maoruibin** [comment]
恩，确实，有同学提到了 `LayoutInflater setFactory` 准备有时间研究下！

**Comment by Rowandjj** [comment]
对的。刚准备说，LayoutInflator#setFactory是个好办法

**Comment by maoruibin** [comment]
恩恩 刚看了 `setFactory` 的相关介绍，如果项目有一个`BaseActivity` 那结合 `LayoutInflator#setFactory` 会很方便啊！我试试

**Comment by maoruibin** [comment]
ReView [1.1.0](https://github.com/maoruibin/ReView/releases/tag/1.1.0) 已经使用 LayoutInflator 的 setFactory 完美解决侵入性的问题！

**Comment by maoruibin** [comment]
ReView [1.1.0](https://github.com/maoruibin/ReView/releases/tag/1.1.0) 已经使用 LayoutInflator 的 setFactory 完美解决侵入性的问题！
