### ISSUE TITLE
demo is right?

### ISSUE THREAD

**Issue by 389273716** [maoruibin/ReView#3]
Your demo is not find such method,like " RVHelper.isReviewMod(true)",but I find this code is right .
`  
                UIReviewSetting.getInstance().isReviewMod(mIsOpen);
`

**Comment by maoruibin** [comment]
`UIReviewSetting` have been change to package access when publish 1.2.0,so i think you should check you dependency version in your local demo. 

``` java
compile project(':library')
or
compile 'com.github.maoruibin:ReView:1.2.0'
```

**Comment by 389273716** [comment]
ok
